# Timeout Time
LAYOUT_TIMEOUT_TIME = 3
TB_NAVIGATE_TIMEOUT = 4
TB_SELECT_TIMEOUT = 4
REGULAR_EXECUTE_TIMEOUT_TIME = 6
# Delays
CAPTURE_SCREENSHOT_DELAY = 2
CAPTURE_STATE_DELAY = 3
REGULAR_EXECUTOR_INTERVAL = 1000
TB_EXECUTOR_INTERVAL = 1000
# Retry
TB_NAVIGATE_RETRY_COUNT = 3
ACTION_EXECUTION_RETRY_COUNT = 2
# Tags
BLIND_MONKEY_TAG = "LATTE_SERVICE"
TB_TREELIST_TAG = "talkback: TreeDebug:"
# Other Limits
EXPLORE_VISIT_LIMIT = 3
