language: python
python:
  - 3.7.6
before_install:
  - python --version
  - pip install -U pip
  - pip install -r requirements.txt
script:
  - cd py_src && python -m unittest test.test_command && cd - # TODO: https://github.com/noidsirius/LatteLibrary/issues/24 
