jobs:
  include:
    - language: python
      python:
        - 3.7.6
      before_install:
        - python --version
        - pip install -U pip
        - pip install codecov
        - pip install coverage
        - pip install -r requirements.txt
      script: cd py_src &&
        coverage run -m unittest discover test &&
        mv .coverage .. &&
        cd - # TODO: https://github.com/noidsirius/LatteLibrary/issues/24
      env:
          - CODECOV_TOKEN=d9615b91-c123-4003-ac18-2df188e88470
      after_success:
        - codecov # submit coverage
    - language: android
      dist: trusty
      jdk:
        - openjdk11
      android:
        components:
          - platform-tools
          - build-tools-29.0.3
          - android-31
          - extra
#      before_install:
 #       - yes | sdkmanager "platform-tools"
#        - yes | sdkmanager "build-tools;29.0.3"
        - yes | sdkmanager "platforms;android-31"
      script:
        - ./gradlew :app:assembleDebug :UseCaseExecutor:check jacocoTestReport
      env:
          - CODECOV_TOKEN=d9615b91-c123-4003-ac18-2df188e88470
      after_success:
        - bash <(curl -s https://codecov.io/bash)
